# Generated by Django 5.0.4 on 2024-04-28 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('time', models.CharField(choices=[('10:00 A.M', '10:00 A.M'), ('10:30 A.M', '10:30 A.M'), ('11:00 A.M', '11:00 A.M'), ('11:30 A.M', '11:30 A.M'), ('12:00 P.M', '12:00 P.M'), ('12:30 P.M', '12:30 P.M'), ('01:00 P.M', '01:00 P.M'), ('01:30 P.M', '01:30 P.M'), ('05:00 P.M', '05:00 P.M'), ('05:30 P.M', '05:30 P.M'), ('06:00 P.M', '06:00 P.M'), ('06:30 P.M', '06:30 P.M'), ('07:00 P.M', '07:00 P.M'), ('07:30 P.M', '07:30 P.M'), ('08:00 P.M', '08:00 P.M'), ('08:30 P.M', '08:30 P.M')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.PositiveIntegerField()),
                ('roomCharge', models.PositiveIntegerField(default=0)),
                ('medicineCost', models.PositiveIntegerField(default=0)),
                ('doctorFee', models.PositiveIntegerField(default=0)),
                ('OtherCharge', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_First_Name', models.CharField(default='', max_length=50)),
                ('Doctor_Last_Name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10)),
                ('address', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('General Physician', 'General Physician'), ('NeuroSurgeon', 'NeuroSurgeon'), ('GastroEntologists', 'GastroEntologists'), ('Pediatrician', 'Pediatrician'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_First_Name', models.CharField(default='', max_length=50)),
                ('Patient_Last_Name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=350)),
                ('symptoms', models.CharField(default='', max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('admitDate', models.DateField(auto_now=True)),
                ('assignedDoctorId', models.PositiveIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
